### ISSUE TITLE
JPG file unopenable.

### ISSUE THREAD

**Issue by Minamkki** [mynameispyo/JcopWebtoonDownloader#3]
I've succesfully downloaded the images however, i am unable to open them. it says the file is not supported or that it's an invalid file despite it being a JPG file.

![ApplicationFrameHost_tzSQTKz04C](https://user-images.githubusercontent.com/79975918/125165155-b91c0300-e1d0-11eb-9a9e-5f00cf2ab803.png)

**Comment by mynameispyo** [comment]
Did you tried to download Lezhin Comics?

**Comment by Minamkki** [comment]
Yes, I've followed all the steps but this happened. Do you have any idea on what may the problem be with authorization?

**Comment by mynameispyo** [comment]
Update the downloader, and try this way
https://github.com/mynameispyo/JcopWebtoonDownloader#find-the-access_token-for-lezhin-comics

**Comment by Minamkki** [comment]
It worked. Thank you very much!
